### ISSUE TITLE
Importing vue-faker to local component has to use 'faker'

### ISSUE THREAD

**Issue by ronyfhebrian** [BrockReece/vue-faker#2]
When I'm not importing vue-faker in global Vue app but rather in component, I cannot use `Import Faker from 'vue-faker'`, but rather `Import faker from 'faker'`.
Is this a bug or is this a featuer?
Thank you.

**Comment by BrockReece** [comment]
`vue-faker` exports a Vue plugin and not a proxy to the faker service. Installing it globally is how it designed to work.
